spring:
  application:
    name: embabel-confluence-mcp-client
  ai:
    mcp:
      client:
        enabled: true
        name: embabel-confluence-mcp-client
        version: 1.0.0
        type: SYNC
        sse:
          connections:
            # Connection to the Confluence MCP Server
            embabel-confluence-mcp-server:
              url: http://localhost:8080/sse # The URL of your MCP server

server:
  port: 8081

embabel:
  models:
    defaultLlm: nex-agi/deepseek-v3.1-nex-n1:free